'use client'

import { useState } from 'react'
import type {
  PublishingIdentity,
  EditorialCommitments,
  AccountabilityFramework,
  MalpublishDefinition,
  CommitmentTemplate,
} from '@/types/database'

interface MalpublishSectionProps {
  identity: PublishingIdentity
  commitments: EditorialCommitments
  accountability: AccountabilityFramework
  templates: CommitmentTemplate[]
  definitions: MalpublishDefinition[]
  onChange: (definitions: MalpublishDefinition[]) => void
}

export function MalpublishSection({
  identity,
  definitions,
  onChange,
}: MalpublishSectionProps) {
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editText, setEditText] = useState('')
  const [customText, setCustomText] = useState('')

  const handleToggle = (id: string) => {
    // Toggle is currently not used - all definitions are included
    // This could be used later if we want users to deselect some
  }

  const handleEdit = (def: MalpublishDefinition) => {
    setEditingId(def.id)
    setEditText(def.text)
  }

  const handleSaveEdit = (id: string) => {
    const updated = definitions.map(d =>
      d.id === id ? { ...d, text: editText } : d
    )
    onChange(updated)
    setEditingId(null)
    setEditText('')
  }

  const handleCancelEdit = () => {
    setEditingId(null)
    setEditText('')
  }

  const handleAddCustom = () => {
    if (!customText.trim()) return

    const newDef: MalpublishDefinition = {
      id: `custom-${Date.now()}`,
      text: customText.trim(),
      is_auto_generated: false,
      is_custom: true,
    }

    onChange([...definitions, newDef])
    setCustomText('')
  }

  const handleRemove = (id: string) => {
    const updated = definitions.filter(d => d.id !== id)
    onChange(updated)
  }

  const autoGenerated = definitions.filter(d => d.is_auto_generated)
  const custom = definitions.filter(d => d.is_custom)

  return (
    <div>
      {/* Transitional header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          You&apos;ve Defined What You Stand For
        </h1>
        <p className="text-xl text-gray-600">
          Now let&apos;s define what you stand against.
        </p>
      </div>

      {/* Explanation box */}
      <div className="max-w-2xl mx-auto mb-8">
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-6">
          <p className="text-gray-700 leading-relaxed mb-3">
            The term <strong>&ldquo;malpublish&rdquo;</strong> was{' '}
            <a href="https://malpublish.org" target="_blank" rel="noopener noreferrer" className="text-[#0074ff] hover:underline">
              coined in 2023
            </a>
            {' '}to describe publishing malpractice—&ldquo;the cause of misinformation.&rdquo;
          </p>
          <p className="text-gray-700 leading-relaxed">
            Based on <strong>your commitments</strong>, here&apos;s
            what malpublishing means for <span className="font-semibold text-blue-700">{identity.organization_name}</span>:
          </p>
        </div>
      </div>

      {/* Auto-generated definitions */}
      <div className="max-w-2xl mx-auto">
        <div className="bg-white rounded-lg border border-gray-200 overflow-hidden mb-6">
          <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
            <h2 className="font-semibold text-gray-900">
              For {identity.organization_name}, malpublishing includes:
            </h2>
          </div>

          <ul className="divide-y divide-gray-100">
            {autoGenerated.map((def) => (
              <li key={def.id} className="p-4">
                {editingId === def.id ? (
                  <div className="space-y-3">
                    <textarea
                      value={editText}
                      onChange={(e) => setEditText(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                      rows={2}
                    />
                    <div className="flex gap-2">
                      <button
                        type="button"
                        onClick={() => handleSaveEdit(def.id)}
                        className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700"
                      >
                        Save
                      </button>
                      <button
                        type="button"
                        onClick={handleCancelEdit}
                        className="px-3 py-1 text-sm text-gray-600 hover:text-gray-800"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3">
                      <span className="text-red-500 mt-0.5">&#x2717;</span>
                      <span className="text-gray-700">{def.text}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => handleEdit(def)}
                      className="text-sm text-gray-500 hover:text-blue-600 shrink-0"
                    >
                      Edit
                    </button>
                  </div>
                )}
                {def.source_commitment && (
                  <p className="text-xs text-gray-400 mt-1 ml-6">
                    Based on your {def.source_commitment.replace('_', ' ')} commitment
                  </p>
                )}
              </li>
            ))}
          </ul>
        </div>

        {/* Custom definitions */}
        {custom.length > 0 && (
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden mb-6">
            <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
              <h2 className="font-semibold text-gray-900">Custom definitions</h2>
            </div>

            <ul className="divide-y divide-gray-100">
              {custom.map((def) => (
                <li key={def.id} className="p-4">
                  {editingId === def.id ? (
                    <div className="space-y-3">
                      <textarea
                        value={editText}
                        onChange={(e) => setEditText(e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                        rows={2}
                      />
                      <div className="flex gap-2">
                        <button
                          type="button"
                          onClick={() => handleSaveEdit(def.id)}
                          className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700"
                        >
                          Save
                        </button>
                        <button
                          type="button"
                          onClick={handleCancelEdit}
                          className="px-3 py-1 text-sm text-gray-600 hover:text-gray-800"
                        >
                          Cancel
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-start gap-3">
                        <span className="text-red-500 mt-0.5">&#x2717;</span>
                        <span className="text-gray-700">{def.text}</span>
                      </div>
                      <div className="flex gap-2 shrink-0">
                        <button
                          type="button"
                          onClick={() => handleEdit(def)}
                          className="text-sm text-gray-500 hover:text-blue-600"
                        >
                          Edit
                        </button>
                        <button
                          type="button"
                          onClick={() => handleRemove(def.id)}
                          className="text-sm text-gray-500 hover:text-red-600"
                        >
                          Remove
                        </button>
                      </div>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Add custom definition */}
        <div className="bg-white rounded-lg border border-gray-200 p-4">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Add a custom malpublishing definition
          </label>
          <div className="flex gap-3">
            <input
              type="text"
              value={customText}
              onChange={(e) => setCustomText(e.target.value)}
              placeholder="Publishing without..."
              className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && customText.trim()) {
                  e.preventDefault()
                  handleAddCustom()
                }
              }}
            />
            <button
              type="button"
              onClick={handleAddCustom}
              disabled={!customText.trim()}
              className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              + Add
            </button>
          </div>
        </div>

        {/* Summary count */}
        <div className="mt-6 text-center text-sm text-gray-500">
          Your policy includes {definitions.length} malpublishing definition{definitions.length !== 1 ? 's' : ''}
        </div>
      </div>
    </div>
  )
}
